"""The two guards standing between autogenerate and the run history.

DERIVED tests. Neither corresponds to a `#### Scenario:` block; both are
asked for by name in the OpenSpec change `replace-cron-with-job-runner`'s
tasks.md (1.1a, 1.6, 1.6b, 1.7), and both exist to protect a requirement
that *is* specified -- `scheduled-jobs`' "Every Run's Outcome Is Recorded
And Can Be Asked About Afterwards". design.md states the hazard plainly:

    once the runner's tables exist in the database and not in that
    metadata, the next `alembic revision --autogenerate` anyone runs --
    for an unrelated feature, months from now -- emits `op.drop_table`
    for every one of them, destroying the run history

and prescribes the remedy this file asserts: "an `include_name`/
`include_object` filter rejecting the runner's table prefix, plus a test
asserting the filter actually names those objects, so removing it fails
rather than silently arming the hazard again".

See `test-manifest.md` at the change root for the full accounting.

## What is invented here

- `FILTER_MODULE` / `FILTER_ATTRIBUTE`: tasks.md 1.6a fixes the
  *directory* (`src/commerce_ops/shared/infrastructure/driven/`) and the
  requirement that the predicate be importable, but no artifact fixes a
  module or function name. This is the single correction point; the
  assertions themselves do not depend on it.
- That the predicate has Alembic's `include_name(name, type_,
  parent_names)` shape rather than `include_object(...)`. design.md names
  both as acceptable; this file assumes the former, since it is the one
  that can reject a table by name without a reflected object to hand.

The runner's own table names are *not* invented, and not transcribed
either: they are read out of the installed runner's schema SQL, so this
file keeps working across a runner upgrade that adds a table -- which is
exactly the upgrade that would otherwise re-arm the hazard silently.

At the time this pass was written the runner is not a dependency of this
project, so every test here is expected to fail on an absent target
(`ModuleNotFoundError`) until tasks 1.1, 1.3 and 1.6 land.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest
from procrastinate import schema

from commerce_ops.shared.infrastructure.driven.alembic_include import include_name

FILTER_MODULE = "commerce_ops.shared.infrastructure.driven.alembic_include"
FILTER_ATTRIBUTE = "include_name"

# The keyword arguments Alembic accepts a name filter under. Both are
# acceptable per design.md; `alembic/env.py` must pass one of them at
# both of its `context.configure()` calls.
FILTER_KEYWORDS = ("include_name", "include_object")


def _repository_root() -> Path:
    for candidate in Path(__file__).resolve().parents:
        if (candidate / "pyproject.toml").is_file():
            return candidate
    pytest.fail("could not locate the repository root from this test's path")


def _runner_table_names() -> list[str]:
    """Every table the installed runner's schema creates.

    Read from the runner itself rather than transcribed, so a runner
    upgrade that adds a table is covered by these assertions the moment it
    is installed.
    """
    sql = schema.SchemaManager.get_schema()
    names = re.findall(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z0-9_.\"]+)",
        sql,
        flags=re.IGNORECASE,
    )
    cleaned = sorted({name.replace('"', "").split(".")[-1] for name in names})
    assert cleaned, "found no CREATE TABLE statements in the runner's schema SQL"
    return cleaned


# --------------------------------------------------------------------------
# tasks.md 1.7: the filter rejects the runner's tables and nothing else
# --------------------------------------------------------------------------


def test_the_filter_rejects_every_table_the_runner_creates() -> None:
    """DERIVED (tasks.md 1.7; design.md, "a hazard that neither branch
    avoids").

    Each of the runner's tables must be excluded from autogenerate's
    comparison, or the next autogenerated migration proposes dropping it
    -- and with it the run history `scheduled-jobs` requires to survive.
    """
    excluded = _runner_table_names()

    still_compared = [
        name
        for name in excluded
        if include_name(name, "table", {"schema_name": None}) is not False
    ]

    assert still_compared == [], (
        "these runner tables are still compared by autogenerate, so the "
        f"next `--autogenerate` run would propose dropping them: {still_compared}"
    )


def test_the_filter_accepts_this_applications_own_tables() -> None:
    """DERIVED (tasks.md 1.7, "and accepts a `products` table").

    A filter that excluded everything would pass the test above while
    disabling autogenerate for the whole project -- silently, and in a way
    that only surfaces as a missing migration months later.
    """
    assert include_name("products", "table", {"schema_name": None}) is not False, (
        "the filter excludes this application's own `products` table, so "
        "autogenerate would stop noticing changes to it"
    )


def test_the_filter_leaves_non_table_names_alone() -> None:
    """DERIVED. design.md's own criterion for the filter's scope: "A
    table-name filter is sufficient because autogenerate's comparison
    covers tables, columns, indexes and constraints".

    A filter that rejected a `schema` name would exclude the default
    schema wholesale, which is a much larger action than the hazard calls
    for.
    """
    assert include_name(None, "schema", {}) is not False
    assert include_name("public", "schema", {}) is not False


# --------------------------------------------------------------------------
# tasks.md 1.6b: the filter is passed at both `context.configure()` calls
# --------------------------------------------------------------------------


def test_both_alembic_configure_calls_receive_the_filter() -> None:
    """DERIVED (tasks.md 1.6b; design.md, "It is passed at both the
    offline and online `context.configure()` calls, so the two paths
    cannot diverge").

    Asserted by reading `alembic/env.py`'s source: that file has no
    package around it and runs `context.config` at import, so it cannot be
    imported here to be inspected at runtime -- which is the same reason
    tasks.md 1.6a gives for putting the predicate in `src/` instead.
    """
    source = (_repository_root() / "alembic" / "env.py").read_text(encoding="utf-8")
    tree = ast.parse(source)

    configure_calls = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "configure"
    ]
    assert len(configure_calls) == 2, (
        "expected the offline and online `context.configure()` calls, found "
        f"{len(configure_calls)}"
    )

    for call in configure_calls:
        keywords = {keyword.arg for keyword in call.keywords}
        assert keywords & set(FILTER_KEYWORDS), (
            f"a `context.configure()` call at line {call.lineno} of "
            "alembic/env.py passes no autogenerate name filter, so that "
            "path would still propose dropping the runner's tables; "
            f"keywords passed: {sorted(str(k) for k in keywords)}"
        )


# --------------------------------------------------------------------------
# tasks.md 1.1a: the vendored schema matches the installed runner
# --------------------------------------------------------------------------


def _migration_sources() -> list[Path]:
    versions = _repository_root() / "alembic" / "versions"
    return sorted(versions.glob("*.py"))


def _normalized(text: str) -> str:
    return " ".join(text.split())


def test_the_migration_vendors_the_installed_runners_schema() -> None:
    """DERIVED (tasks.md 1.1a, 1.4a).

    `>=3.9,<4` permits a minor upgrade that ships schema migrations;
    without this assertion, a routine `uv lock --upgrade` would run newer
    runner code against the tables an older revision installed -- failing
    at runtime, in the window before `report-overdue-scheduled-runs` can
    report it.

    Compared with whitespace normalized: what must match is the schema's
    content, not how the migration happens to indent a vendored SQL
    literal. If a future migration deliberately vendors a *modified*
    schema, that is a decision to record in the change proposing it, not
    an assertion to relax here.
    """
    installed = _normalized(schema.SchemaManager.get_schema())

    vendoring = [
        path
        for path in _migration_sources()
        if _normalized(path.read_text(encoding="utf-8")).find(installed) != -1
    ]

    mentioning = [
        path.name
        for path in _migration_sources()
        if "procrastinate" in path.read_text(encoding="utf-8")
    ]
    assert vendoring, (
        "no Alembic migration vendors the installed runner's schema SQL "
        f"verbatim; migrations mentioning the runner: {mentioning or 'none'}"
    )
